### ISSUE TITLE
Should work on .tsx files as well

### ISSUE THREAD

**Issue by urbanhop** [adiessl/vscode-backtix#2]
currently only applies to .ts

**Comment by adiessl** [comment]
Glad you figured out how to enable it.

The reason why I chose not to enable it by default for `.jsx`/`.tsx` is that I am not using React. I just briefly tested it with one small sample file. Since that worked I included the options for enabling it. But I was not sure if that test file included all edge cases. 

Now if you use React and could test it for a couple of days and give me some feedback, I would happily enable it by default – knowing everything works well and as expected.

Thanks for using BacktiX!
